import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { EstimateResponse } from "./api";
import { formatPKR } from "./utils";

export function generateEstimatePDF(data: EstimateResponse) {
  const doc = new jsPDF();
  
  // Header
  doc.setFillColor(16, 42, 67); // Navy 800
  doc.rect(0, 0, 210, 30, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.text("Tameer.ai", 14, 20);
  doc.setFontSize(10);
  doc.text("Autonomous Construction & Renovation Estimator", 70, 20);

  // Requirements Summary
  doc.setTextColor(30, 41, 59);
  doc.setFontSize(14);
  doc.text("Project Requirements", 14, 45);
  
  doc.setFontSize(10);
  const reqs = data.requirements;
  doc.text(`Plot Size: ${reqs.plot_size} ${reqs.plot_unit}`, 14, 55);
  doc.text(`Floors: ${reqs.floors}`, 80, 55);
  doc.text(`Quality Tier: ${reqs.quality_tier}`, 150, 55);
  doc.text(`Rooms: ${reqs.bedrooms} Bed, ${reqs.bathrooms} Bath, ${reqs.kitchens} Kitchen`, 14, 62);
  doc.text(`Covered Area: ${data.cost_summary.covered_area_sqft} sq ft`, 80, 62);

  // Cost Summary
  doc.setFontSize(14);
  doc.text("Cost Summary", 14, 75);
  
  const summaryData = [
    ["Grey Structure", formatPKR(data.cost_summary.grey_structure_total)],
    ["Finishing", formatPKR(data.cost_summary.finishing_total)],
    ["Services", formatPKR(data.cost_summary.services_total)],
    ["Labor", formatPKR(data.cost_summary.labor_total)],
    ["Contingency (8%)", formatPKR(data.cost_summary.contingency_total)],
    ["Grand Total", formatPKR(data.cost_summary.grand_total)],
    ["Cost per Sq Ft", formatPKR(data.cost_summary.cost_per_sqft)],
  ];

  autoTable(doc, {
    startY: 80,
    head: [["Category", "Estimated Cost (PKR)"]],
    body: summaryData,
    theme: 'grid',
    headStyles: { fillColor: [16, 185, 129] }, // Emerald 500
    foot: [["Grand Total", formatPKR(data.cost_summary.grand_total)]],
    footStyles: { fillColor: [16, 42, 67] }
  });

  // BOQ Table
  doc.addPage();
  doc.setFontSize(14);
  doc.text("Bill of Quantities (BOQ)", 14, 20);

  const boqData = data.boq.map(item => [
    item.category.replace('_', ' ').toUpperCase(),
    item.item.toUpperCase(),
    `${item.quantity} ${item.unit}`,
    formatPKR(item.rate_pkr),
    formatPKR(item.amount_pkr)
  ]);

  autoTable(doc, {
    startY: 25,
    head: [["Category", "Item", "Quantity", "Rate", "Total Amount"]],
    body: boqData,
    theme: 'striped',
    headStyles: { fillColor: [16, 42, 67] },
  });

  // Timeline
  doc.addPage();
  doc.setFontSize(14);
  doc.text("Project Timeline & Milestones", 14, 20);

  const timelineData = data.timeline.map(phase => [
    phase.name,
    `Week ${phase.start_week}`,
    `${phase.duration_weeks} Weeks`,
    `${phase.payment_milestone_percent}%`
  ]);

  autoTable(doc, {
    startY: 25,
    head: [["Phase", "Starts", "Duration", "Payment Milestone"]],
    body: timelineData,
    theme: 'grid',
    headStyles: { fillColor: [16, 42, 67] },
  });

  // Footer / Disclaimer
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
      "Disclaimer: Estimates are indicative and generated by AI. Always verify rates and quantities in your local market.",
      14,
      290
    );
  }

  doc.save(`Tameer_Estimate_${new Date().getTime()}.pdf`);
}
